[tool.poetry]
name = "minesweeper"
version = "0.1.0"
description = ""
authors = ["cebrianj"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
textual = "^0.58.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
